version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lbw
      MYSQL_USER: lbw
      MYSQL_PASSWORD: miqlbw02
    ports:
      - "3306:3306"


  # Layanan untuk aplikasi Flask
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+mysqlconnector://lbw:miqlbw02@mysql/lbw?charset=utf8mb4&collation=utf8mb4_general_ci"
      SECRET_KEY: miqlbw02
